export const blogInfo = [
  {
    id: 1,
    img: "/public/blogs/blog.jpg",
    by1: "John Doe",
    by2: "Sep 22, 2020",
    by3: "0 Comments",
    title: "Sed adipiscing ornare.",
    category1: "Lifestyle",
    category2: "Shopping",
    date: "Nov 22, 2018",
    desc: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
  },
  {
    id: 2,
    img: "/public/blogs/blog2.jpg",
    by1: "John Doe",
    by2: "Sep 22, 2020",
    by3: "0 Comments",
    title: "Sed adipiscing ornare.",
    category1: "Lifestyle",
    category2: "Shopping",
    date: "Nov 22, 2018",
    desc: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
  },
  {
    id: 3,
    img: "/public/blogs/blog3.jpg",
    by1: "John Doe",
    by2: "Sep 22, 2020",
    by3: "0 Comments",
    title: "Sed adipiscing ornare.",
    category1: "Lifestyle",
    category2: "Shopping",
    date: "Nov 22, 2018",
    desc: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
  },
  {
    id: 4,
    img: "/public/blogs/blog4.jpg",
    by1: "John Doe",
    by2: "Sep 22, 2020",
    by3: "0 Comments",
    title: "Sed adipiscing ornare.",
    category1: "Lifestyle",
    category2: "Shopping",
    date: "Nov 22, 2018",
    desc: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh ...",
  },
];
